
language: cpp
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libx11-dev libogg-dev libxft-dev libpulse-dev rpm debhelper

branches:
  only:
    - development

script: mkdir ../build && cd ../build && cmake ../NeoEditor && make && make package && make test

notifications:
  irc: "chat.freenode.net#neo3d"