language: cpp
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y libx11-dev libogg-dev libxft-dev libpulse-dev rpm debhelper
branches:
  only:
  - development
script: mkdir ../build && cd ../build && cmake ../NeoEditor && make && make package
  && make test
notifications:
  irc: chat.freenode.net#neo3d
env:
  global:
  - secure: gRfErdM33brK8kCNMdWXNqRogtUIHgzRDYAbnxxr5Ux3UjEwSFHaLJKaDGd4lJimZ1HUJEr6Z//pRAuYx497msZ/zdwgzsy1zKXSOEOywA50NMLS7da7feMujZ65Cqwxzmwq6ge6woOClLQmNZo/w6jI89DSXU/JMa5N8/VcMvA=
  - secure: gjuBvU55Hnf+J/t3f4xyFlNVq51DcTQvslKQHXwvV4GQg1pZYS2dRtGCkpASja+2MnnJ5MFBUcUctQQMVRC17VQzoccLodFnKfMcOuFLeJwayp943MinUad4KsoOzLQECW06B2hzc90hfkV29TqaQcQM+s6uEOn21gPG4zrIM/k=
  
after_success:
  - curl --ftp-create-dirs -T *.deb -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/
  - curl --ftp-create-dirs -T *.tar.gz -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/
  - curl --ftp-create-dirs -T *.rpm -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/
  - curl --ftp-create-dirs -T *.sh -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/

